user:
  name:
    max_length: 50
  email:
    max_length: 255
  option_size: 80
  password:
    min_length: 6
  avatar_size: 50
  per_page_size: 10
micropost:
  content:
    max_length: 140
  hour_expired: 2
  size: 5
